url: "https://zastrow.github.io/container-query-demo/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/" # the subpath of your site, e.g. /blog
title: "Container Query Demo" # the name of your site, e.g. ACME Corp.
